name: Run Ubuntu Server with XFCE and RustDesk

on: [push]

jobs:
  run-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Change root password
        run: |
          echo "root:khantmgmg1412" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart
          
      - name: Install cloudflare tunnel
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb 
          sudo dpkg -i cloudflared.deb
          sudo cloudflared service install eyJhIjoiNmExMWM3ZmI0N2U0M2M5YjQ2NjgyZGE0YTk4NDQ1ZjYiLCJ0IjoiMDIzOTUzNTctZDgxMC00NzY5LWFjZDItOWI1NGJkMjNhYmI3IiwicyI6Ik9UWm1NV1UwTlRndFlUY3hZaTAwWVdJMUxXSXhNVEF0TkdZMlpEQTBabVZrWVRBNSJ9

      - name: Run Python script
        run: |
          # Create the Python script
          touch python_script.py
          echo "import time
  
          while True:
              print('Python script executed')
              time.sleep(60)" > python_script.py
  
          # Run the script and capture its output
          output=$(python3 python_script.py)
  
          # Print the output to the console
          echo "$output"
