name: Run Ubuntu Server with XFCE and RustDesk

on: [push]

jobs:
  run-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Removing older version of docker from machine
        run: |
          for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
      
      - name: Adding Docker's official GPG key
        run: |
          # Add Docker's official GPG key:
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

      - name: Install docker
        run: |
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      
      - name: Change root password
        run: |
          echo "root:${{ secrets.ROOT_PASSWORD }}" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart
      - name: Download and install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          ngrok authtoken ${{ secrets.NGROK_KEY }}  # Store your Ngrok authtoken in GitHub Secrets      

      - name: Install cloudflare tunnel
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb 
          sudo dpkg -i cloudflared.deb
          sudo cloudflared service install eyJhIjoiNmExMWM3ZmI0N2U0M2M5YjQ2NjgyZGE0YTk4NDQ1ZjYiLCJ0IjoiMDIzOTUzNTctZDgxMC00NzY5LWFjZDItOWI1NGJkMjNhYmI3IiwicyI6Ik9UWm1NV1UwTlRndFlUY3hZaTAwWVdJMUxXSXhNVEF0TkdZMlpEQTBabVZrWVRBNSJ9

      - name: Run Python script
        run: |
          # Create the Python script
          touch python_script.py
          echo "import time
  
          while True:
              print('Python script executed')
              time.sleep(60)" > python_script.py
  
          # Run the script and capture its output
          output=$(python3 python_script.py)
  
          # Print the output to the console
          echo "$output"
