name: Run Ubuntu Server

on: [push]

jobs:
  run-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Run Python script
      run: |
        # Create the Python script
        touch python_script.py
        echo "import time
    
        while True:
            print('Python script executed')
            time.sleep(60)" > python_script.py
    
        # Run the script and capture its output
        output=$(python3 python_script.py)
    
        # Print the output to the console
        echo "$output"
